### ISSUE TITLE
Need average of three numbers

### ISSUE THREAD

**Issue by jakelazaroff** [emilyschultz/Advanced-Programming#1]
Function at https://github.com/emilyschultz/Advanced-Programming/blob/master/Lab1/main.c#L40 only supports two numbers, but I need to find the average of three 😰

**Comment by emilyschultz** [comment]
Thanks for your input! I love your twitter @lakejazaroff. 
May I direct you to the [problem description](https://github.com/emilyschultz/Advanced-Programming/blob/master/Lab1/lab1description.pdf), where it specifies an input of *2* numbers?

But, to help you out, feel free to fork the repo and add:
```
double average(int a, int b, int c)
{
  return (a + b + c) / 3.0;
}
```
-ya girl em
